data_splits:
  train:
    start: "2007-01"
    end: "2017-03"
  xgboost_val:
    start: "2017-04"
    end: "2018-01"
  optuna_val:
    start: "2018-02"
    end: "2018-05"
  test:
    start: "2018-06"
    end: "2018-12"

monotone_constraints:
  pct_tl_nvr_dlq: 1
  emp_length: 1
  emp_length/term: 1
  annual_inc: 1
  acc_satisfied_rate: 1
  bc_open_to_buy: 1
  total_bc_limit: 1
  credit_history_months: 1
  mths_since_last_record: 1
  mths_since_last_delinq: 1

  num_tl_90g_dpd_24m: -1
  pub_rec_bankruptcies: -1
  total_bal/inc: -1
  loan/term: -1
  percent_bc_gt_75: -1
  delinq_2yrs: -1
  collections_12_mths_ex_med: -1
  delinq_amnt: -1
  revol_util: -1
  bc_util: -1
  il_util: -1
  unemployment_rate: -1
  dti: -1

nuissance_params:
  n_estimators: 20
  max_depth: 6
  learning_rate: 0.3
  #device: cuda